#! /bin/sh

# this script installs a fresh version of quicklisp to the current user's
# homedir.

gpg --verify /usr/local/src/quicklisp/quicklisp.lisp.asc /usr/local/src/quicklisp/quicklisp.lisp

sbcl --no-sysinit --no-userinit --non-interactive \
     --load /usr/local/src/quicklisp/quicklisp.lisp \
     --eval "(quicklisp-quickstart:install :path \"/usr/local/share/common-lisp/quicklisp/\")"\
     --eval "(ql::without-prompting (dolist (imp '(:sbcl :ccl)) (ql:add-to-init-file imp)))"
